[package]
name = "mini-zinc"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
approx = "0.5.1"
bytemuck = "1.22.0"
byteorder = "1.5.0"
half = { version = "2.6.0", features = ["serde"] }
ndarray = { version = "0.16.1", features = ["rayon", "serde"]}
nom = "8.0.0"
ocl = "0.19.7"
rand = "0.9.0"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"]}
serde_json = "1.0"
tempfile = "3.19.1"
tokio = { version = "1.44.2", features = ["full"] }
warp = "0.3.7"
zip = { version = "2.6.1", features = ["deflate"]}

[dev-dependencies]
tempfile = "3.19.1"
